@baseUrl = http://localhost:3000
@username = 12341234
@email = 12341234@example.com
@password = 12341234
@sessionToken = im8yW7DxcbAik7QI8UUNildXDNFqwGxc
@csrfToken = U1Sb0N3vQMhxfuzwsGdZgXpn0Xre8yBv
@postID = 01KBE8AG5K73NMM90GD8DHKRZ7

############################## Health

GET {{baseUrl}}/api/health

############################## Version

GET {{baseUrl}}/api/version

################################ Auth

POST {{baseUrl}}/api/auth/sign-up
Content-Type: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "password": "{{password}}",
  "languageCode": "zh-HK"
}

###

POST {{baseUrl}}/api/auth/pre-session

###

POST {{baseUrl}}/api/auth/sign-in
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

POST {{baseUrl}}/api/auth/sign-out
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

###

POST {{baseUrl}}/api/auth/sign-out-all
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

###

GET {{baseUrl}}/api/auth/csrf-token
Cookie: issho_session_token={{sessionToken}}

############################ User

GET {{baseUrl}}/api/users/me
Cookie: issho_session_token={{sessionToken}}

###

DELETE {{baseUrl}}/api/users/me
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

###

PATCH {{baseUrl}}/api/users/me/username
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "newUsername": "12341234"
}

############################ Post

POST {{baseUrl}}/api/posts
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "title": "New Post",
  "description": "This is a new post",
  "content": "Post content goes here",
  "publishedAt": "2023-01-07T00:00:00.000Z"
}

###

GET {{baseUrl}}/api/posts?&pageSize=10
Cookie: issho_session_token={{sessionToken}}

###

GET {{baseUrl}}/api/posts/{{postID}}
Cookie: issho_session_token={{sessionToken}}

###

PUT {{baseUrl}}/api/posts/{{postID}}
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "title": "Updated Post",
  "description": "This is an updated post",
  "content": "Updated post content goes here",
  "publishedAt": "2023-02-01T00:00:00.000Z"
}

###

DELETE {{baseUrl}}/api/posts/{{postID}}
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}