@baseUrl = http://localhost:3000
@username = 123412345
@password = 12341234
@sessionToken = RCXNzyFBFrOS4xIHd1ntJ1oMVz6ms3Yh
@csrfToken = 0aLWJtDgVRHUwZueAqJ79g7RI6KK08Ds

############################## Health

GET {{baseUrl}}/api/health

############################## Version

GET {{baseUrl}}/api/version

################################ Auth

POST {{baseUrl}}/api/auth/sign-up
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

POST {{baseUrl}}/api/auth/pre-session

###

POST {{baseUrl}}/api/auth/sign-in
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

POST {{baseUrl}}/api/auth/sign-out
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

###

POST {{baseUrl}}/api/auth/sign-out-all
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

###

GET {{baseUrl}}/api/auth/csrf-token
Cookie: issho_session_token={{sessionToken}}

############################ User

GET {{baseUrl}}/api/users/me
Cookie: issho_session_token={{sessionToken}}

###

DELETE {{baseUrl}}/api/users/me
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

###

PATCH {{baseUrl}}/api/users/me/username
Cookie: issho_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "newUsername": "12341234"
}
